### ISSUE TITLE
permission denied with docker

### ISSUE THREAD

**Issue by gsw945** [opensumi/ide-startup#84]
docker-compose方式运行

workspace中创建文件没有权限
![image](https://github.com/opensumi/ide-startup/assets/6281968/89358680-6542-46c9-a0ef-c1b79bca2d03)

终端中尝试创建也提示没有权限
![image](https://github.com/opensumi/ide-startup/assets/6281968/9390b5a4-5127-49bf-8909-57682c9addf9)

---
`docker-compose.yml`如下:
```yaml
version: '3'
services:
  opensumi:
    image: ghcr.io/opensumi/opensumi-web:v1.20.0
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "9000:8000" # HTTP
    user: "1000:1000"
```
